// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehhlvuvxxnoodnvborsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoaGx2dXZ4eG5vb2RudmJvcnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDMwMzMsImV4cCI6MjA3MDc3OTAzM30.vTlyYmxzGhLsChHs6jrIg6_HyyRkQE99f45fVZ5SFMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});